[package]
name = "ps4-repo-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
data-encoding = "2.6.0"
ring = "0.17.8"
rusqlite = "0.32.1"
serde = "1.0.209"
serde_derive = "1.0.209"
serde_json = "1.0.127"
toml = "0.8.19"
walkdir = "2.5.0"
